### ISSUE TITLE
Encrypted private key can not used to deploy ACS template

### ISSUE THREAD

**Issue by zhang-hua** [Azure/pcs-cli#138]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

E:\Workspace\Github\Azure\pcs-cli\node_modules\ssh2\lib\client.js:235
        throw new Error('Encrypted private key detected, but no passphrase given');
        ^

Error: Encrypted private key detected, but no passphrase given
    at Client.connect (E:\Workspace\Github\Azure\pcs-cli\node_modules\ssh2\lib\client.js:235:15)
    at Timeout.setInterval [as _onTimeout] (E:\Workspace\Github\Azure\pcs-cli\publish\deploymentmanager.js:238:22)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

# Steps to reproduce

1. run 'pcs login'
2. run 'pcs -t remotemonitoring -s standard'
3. in the Q&A menu, pick up a ssh key which has protected by passphrase
4. see errors but reported "Deployed successfully..."

**Comment by ppathan** [comment]
wontfix
