### ISSUE TITLE
InvalidAuthenticationTokenTenant error when deploying Remote Monitoring Solution in Standard config

### ISSUE THREAD

**Issue by darenm** [Azure/pcs-cli#357]
# Type of issue 

- [X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

Issuing this command

```cmd
pcs -t remotemonitoring -s standard
```

Results in the error shown below. I have two subscriptions on the same account, so I wonder if the problem is that a domain qualifier is required?

error:
```csharp
{ Error: The access token is from the wrong issuer 'https://sts.windows.net/<removed>/'. It must match the tenant 'https://sts.windows.net/<removed>/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/<removed>' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
    at client.pipeline (C:\Users\daren\AppData\Roaming\npm\node_modules\iot-solutions\node_modules\azure-arm-authorization\lib\operations\roleAssignments.js:617:19)
    at retryCallback (C:\Users\daren\AppData\Roaming\npm\node_modules\iot-solutions\node_modules\ms-rest\lib\filters\systemErrorRetryPolicyFilter.js:89:9)
    at retryCallback (C:\Users\daren\AppData\Roaming\npm\node_modules\iot-solutions\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:9)
    at C:\Users\daren\AppData\Roaming\npm\node_modules\iot-solutions\node_modules\ms-rest\lib\filters\rpRegistrationFilter.js:59:14
    at handleRedirect (C:\Users\daren\AppData\Roaming\npm\node_modules\iot-solutions\node_modules\ms-rest\lib\filters\redirectFilter.js:39:9)
    at C:\Users\daren\AppData\Roaming\npm\node_modules\iot-solutions\node_modules\ms-rest\lib\filters\formDataFilter.js:23:14
    at Request.defaultRequest [as _callback] (C:\Users\daren\AppData\Roaming\npm\node_modules\iot-solutions\node_modules\ms-rest\lib\requestPipeline.js:125:16)
    at Request.self.callback (C:\Users\daren\AppData\Roaming\npm\node_modules\iot-solutions\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\daren\AppData\Roaming\npm\node_modules\iot-solutions\node_modules\request\request.js:1161:10)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\daren\AppData\Roaming\npm\node_modules\iot-solutions\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  statusCode: 401,
  request:
   { rawResponse: false,
     queryString: {},
     url: 'https://management.azure.com//subscriptions/<removed>/providers/Microsoft.Authorization/roleAssignments/<removed>?api-version=2015-07-01',
     method: 'PUT',
     headers:
      { 'Content-Type': 'application/json; charset=utf-8',
        'x-ms-client-request-id': '<removed>',
        'accept-language': 'en-US',
        'user-agent': 'Node/v8.9.3 (x64-Windows_NT-10.0.17758) ms-rest/2.3.4 ms-rest-azure/2.5.7 azure-arm-authorization/4.1.0 Azure-SDK-For-Node' },
     body: '{"properties":{"roleDefinitionId":"/subscriptions/<removed>/providers/Microsoft.Authorization/roleDefinitions/<removed>","principalId":"<removed>"}}' },
  response:
   { body: '{"error":{"code":"InvalidAuthenticationTokenTenant","message":"The access token is from the wrong issuer \'https://sts.windows.net/<removed>/\'. It must match the tenant \'https://sts.windows.net/<removed>/\' associated with this subscription. Please use the authority (URL) \'https://login.windows.net/<removed>\' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."}}',
     headers:
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'www-authenticate': 'Bearer authorization_uri="https://login.windows.net/781de9ba-95b5-4eec-8884-6ac05b90cabb", error="invalid_token", error_description="The access token is from the wrong issuer. It must match the tenant associated with this subscription. Please use correct authority to get the token."',
        'x-ms-failure-cause': 'gateway',
        'x-ms-request-id': <removed>',
        'x-ms-correlation-request-id': '<removed>',
        'x-ms-routing-request-id': 'WESTCENTRALUS:20180913T184107Z<removed>',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'x-content-type-options': 'nosniff',
        date: 'Thu, 13 Sep 2018 18:41:07 GMT',
        connection: 'close',
        'content-length': '677' },
     statusCode: 401 },
  code: 'InvalidAuthenticationTokenTenant',
  body:
   { code: 'InvalidAuthenticationTokenTenant',
     message: 'The access token is from the wrong issuer \'https://sts.windows.net/<removed>/\'. It must match the tenant \'https://sts.windows.net/<removed>/\' associated with this subscription. Please use the authority (URL) \'https://login.windows.net/<removed>\' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.' } }
{
  "statusCode": 401,
  "request": {
    "rawResponse": false,
    "queryString": {},
    "url": "https://management.azure.com//subscriptions/<removed>/providers/Microsoft.Authorization/roleAssignments/<removed>?api-version=2015-07-01",
    "method": "PUT",
    "headers": {
      "Content-Type": "application/json; charset=utf-8",
      "x-ms-client-request-id": "2ba25a7b-c1a1-49a4-810f-1e90c32272ac",
      "accept-language": "en-US",
      "user-agent": "Node/v8.9.3 (x64-Windows_NT-10.0.17758) ms-rest/2.3.4 ms-rest-azure/2.5.7 azure-arm-authorization/4.1.0 Azure-SDK-For-Node"
    },
    "body": "{\"properties\":{\"roleDefinitionId\":\"/subscriptions/<removed>/providers/Microsoft.Authorization/roleDefinitions/<removed>5\",\"principalId\":\"<removed>\"}}"
  },
  "response": {
    "body": "{\"error\":{\"code\":\"InvalidAuthenticationTokenTenant\",\"message\":\"The access token is from the wrong issuer 'https://sts.windows.net/<removed>/'. It must match the tenant 'https://sts.windows.net/<removed>/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/<removed>' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.\"}}",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-type": "application/json; charset=utf-8",
      "expires": "-1",
      "www-authenticate": "Bearer authorization_uri=\"https://login.windows.net/<removed>\", error=\"invalid_token\", error_description=\"The access token is from the wrong issuer. It must match the tenant associated with this subscription. Please use correct authority to get the token.\"",
      "x-ms-failure-cause": "gateway",
      "x-ms-request-id": "<removed>",
      "x-ms-correlation-request-id": "<removed>",
      "x-ms-routing-request-id": "WESTCENTRALUS:20180913T184107Z:<removed>",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "x-content-type-options": "nosniff",
      "date": "Thu, 13 Sep 2018 18:41:07 GMT",
      "connection": "close",
      "content-length": "677"
    },
    "statusCode": 401
  },
  "code": "InvalidAuthenticationTokenTenant",
  "body": {
    "code": "InvalidAuthenticationTokenTenant",
    "message": "The access token is from the wrong issuer 'https://sts.windows.net/<removed>/'. It must match the tenant 'https://sts.windows.net/<removed>/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/<removed>' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."
  }
}
```
...

# Steps to reproduce 

1. Have a multi-tenant azure account
2. pcs -t remotemonitoring -s standard
3. Boom!

# Expected behavior 

Successful deploy.
...

# Current behavior 

* I created a new user within my tenant
* I set the user to be a co-admin on a single subscription
* I set that subscription to be default using azure cli
* used that user to login `pcs login`

`pcs -t remotemonitoring -s standard` then succeeded
...

# Possible solution 

Detect if there are multiple tenants and prompt for a tenant qualifier?
...

# Context and Environment
* Operating System: Windows 10 1809 17758.1
* GitHub branch: ...
* Node.js Runtime: v8.9.3

**Comment by darenm** [comment]
Just noticed that pcs has a `--domainId` option - trying that...

**Comment by asdonald** [comment]
#359 is the fix for this issue. Please let us know if you have any more questions.
