### ISSUE TITLE
Local deploy error 

### ISSUE THREAD

**Issue by Dolphinsimon** [Azure/pcs-cli#490]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

Local deploy error : Error: Cannot find module '/user/azure-iot-pcs-remote-monitoring-dotnet/pcs-cli/publish/solutions/remotemonitoring/armtemplates/local-static-map.json

# Steps to reproduce 

1. run  pcs -t remotemonitoring -s local
2. after Application registered.
3. { Error: Cannot find module '/user/azure-iot-pcs-remote-monitoring-dotnet/pcs-cli/publish/solutions/remotemonitoring/armtemplates/local-static-map.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at DeploymentManager.submit (/root/azure-iot-pcs-remote-monitoring-dotnet/pcs-cli/publish/deploymentmanager.js:74:30)
    at subPrompt.then.then.then.then.then.then (/root/azure-iot-pcs-remote-monitoring-dotnet/pcs-cli/publish/index.js:305:54)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) code: 'MODULE_NOT_FOUND' }

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: Ubuntu 18.04
* GitHub branch: master
* Node.js Runtime: 8.15.1

**Comment by ppathan** [comment]
Did you do a build, by running `npm start`? The file will be added to the publish folder after that.

**Comment by Dolphinsimon** [comment]
Not yet. But I installed the package by 'npm install iot-solutions -g'. Do I need to run npm start?
I just followed the steps in [https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-cli](url)

**Comment by sushilraje** [comment]
This is a bug. Needs to be fixed.
