### ISSUE TITLE
Subscriptions could not be loaded in AZ Storage Explorer

### ISSUE THREAD

**Issue by runningman19** [Azure/pcs-cli#539]
# Type of issue 

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

I captured the 'more information' details.  Pasted below.  I researched other bug reports but no resolution.  I am not using a proxy.  

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 6085de46-5c5f-404e-bdc2-2a7227ddce84, Error: {
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
  "__zone_symbol__error": {
    "originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
    "zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)"
  },
  "stack": "Error: getaddrinfo ENOTFOUND management.azure.com management.azure.com:443\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "__zone_symbol__stack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
  "__zone_symbol__originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "__zone_symbol__zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "errno": "ENOTFOUND",
  "code": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "management.azure.com",
  "host": "management.azure.com",
  "port": 443
}
Tenant Id: 604c1504-c6a3-4080-81aa-b33091104187, Error: {
  "name": "Error",
  "message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
  "__zone_symbol__error": {
    "originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
    "zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)"
  },
  "stack": "Error: getaddrinfo ENOTFOUND management.azure.com management.azure.com:443\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "__zone_symbol__stack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "__zone_symbol__name": "Error",
  "__zone_symbol__message": "getaddrinfo ENOTFOUND management.azure.com management.azure.com:443",
  "__zone_symbol__originalStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "__zone_symbol__zoneAwareStack": "Error: getaddrinfo ENOTFOUND management.azure.com\n    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:811:33)\n    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\applicationinsights\\out\\AutoCollection\\CorrelationContextManager.js:193:18)\n    at dnsException (internal/errors.js:380:14)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)",
  "errno": "ENOTFOUND",
  "code": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "management.azure.com",
  "host": "management.azure.com",
  "port": 443
}

I was following this exercise:
https://docs.microsoft.com/en-us/learn/modules/upload-download-and-manage-data-with-azure-storage-explorer/3-exercise-connect-storage-account

I'm not even certain this is the correct area to report this error for help.
...

# Steps to reproduce 

1. [Launch Az Storage Explorer]
2. [go to account management.  ]
3. [Add account, logged in and the message displayed.]

# Expected behavior <a successful import mof my existing subscription->
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...windows 
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by runningman19** [comment]
It works now.  If I ever am able to repeat the issue (and then 'fix' it)  I will indicate the resolution.

**Comment by runningman19** [comment]
Well that didn't take me long.   It seems that when I have VPN'd in i get the unable to load subscriptions.  I disconnect and it loads.  Above my pay grade to explain that just yet.

Cheers
