### ISSUE TITLE
Error: Long running operation failed with error: "Entry not found in cache.".

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-cli#69]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
```
# pcs
? Enter a solution name: mytest
? Select a subscription: mysub
? Select a location West US
? Enter a user name for the virtual machine me
? Enter a password ************
✓ Provisioning State: Succeeded	Resource Type: Microsoft.Network/publicIPAddresses
✓ Provisioning State: Succeeded	Resource Type: Microsoft.Network/networkInterfaces
✓ Provisioning State: Succeeded	Resource Type: Microsoft.Storage/storageAccounts
✓ Provisioning State: Succeeded	Resource Type: Microsoft.Network/networkInterfaces
✓ Provisioning State: Succeeded	Resource Type: Microsoft.Network/publicIPAddresses
✓ Provisioning State: Succeeded	Resource Type: Microsoft.Network/virtualNetworks
✓ Provisioning State: Succeeded	Resource Type: Microsoft.Network/networkSecurityGroups
/ Provisioning State: Running	Resource Type: Microsoft.Compute/virtualMachines
/ Provisioning State: Running	Resource Type: Microsoft.Devices/Iothubs
/ Provisioning State: Running	Resource Type: Microsoft.DocumentDb/databaseAccounts
- Deploying...(node:27787) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 138): Error: Long running operation failed with error: "Entry not found in cache.".
(node:27787) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
- Deploying...
```

**Comment by kjayantmenon** [comment]
I'm still seeing a similar kind of issue. Unsure if it is related to the AAD 
Error: Entry not found in cache.
    at Logger.createError (C:\home\code\unilever\pcs-cli\node_modules\adal-node\lib\log.js:216:13)
    at TokenRequest.<anonymous> (C:\home\code\unilever\pcs-cli\node_modules\adal-node\lib\token-request.js:526:40)
    at C:\home\code\unilever\pcs-cli\node_modules\adal-node\lib\token-request.js:148:20
    at C:\home\code\unilever\pcs-cli\node_modules\adal-node\lib\cache-driver.js:366:7
    at C:\home\code\unilever\pcs-cli\node_modules\adal-node\lib\cache-driver.js:301:7
    at Request._callback (C:\home\code\unilever\pcs-cli\node_modules\adal-node\lib\util.js:130:7)
    at Request.self.callback (C:\home\code\unilever\pcs-cli\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\home\code\unilever\pcs-cli\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\home\code\unilever\pcs-cli\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by kjayantmenon** [comment]
I'm still seeing this error. Not sure if it is related to the same AAD issue - 

Error: Entry not found in cache.
    at Logger.createError (C:\home\code\U$#%*\pcs-cli\node_modules\adal-node\lib\log.js:216:13)
    at TokenRequest.<anonymous> (C:\home\code\U$#%*\pcs-cli\node_modules\adal-node\lib\token-request.js:526:40)
    at C:\home\code\U$#%*\pcs-cli\node_modules\adal-node\lib\token-request.js:148:20
    at C:\home\code\U$#%*\pcs-cli\node_modules\adal-node\lib\cache-driver.js:366:7
    at C:\home\code\U$#%*\pcs-cli\node_modules\adal-node\lib\cache-driver.js:301:7
    at Request._callback (C:\home\code\U$#%*\pcs-cli\node_modules\adal-node\lib\util.js:130:7)
    at Request.self.callback (C:\home\code\U$#%*\pcs-cli\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\home\code\U$#%*\pcs-cli\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\home\code\U$#%*\pcs-cli\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by nasirvi** [comment]
Hi @kjayantmenon, Actually I am also facing the same issue so wanted to know if you have resolved this issue.

**Comment by jillcary** [comment]
Hello,

This issue is related to the Azure login and can be caused for many possible reasons. One reason that is known is due to mutli-factor auth.

You can also try logging out and logging back in, or using `azure account clear` and signing back in.

**Comment by nasirvi** [comment]
Running "azure account clear" didn't solve the issue for me. I changed my password for some purpose and it solved the issue

**Comment by alicejgibbons** [comment]
I am still getting this error running pcs login. Changed password, ran "az account clear", "pcs logout" did not solve it for me...
